name: finale
description: "A comprehensive Flutter project with modern dependencies and configurations."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.7.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Core UI and Design
  cupertino_icons: ^1.0.8
  intl: ^0.18.1

  # State Management
  provider: ^6.1.1
  
  # Navigation
  go_router: ^13.2.1

  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  
  # Utilities
  dartz: ^0.10.1
  equatable: ^2.0.5
  
  # Network
  dio: ^5.4.1

  # Charts and Visualization
  fl_chart: ^0.67.0

  # Additional Useful Packages
  cached_network_image: ^3.3.1
  shared_preferences: ^2.2.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  
  # Testing
  mockito: ^5.4.4
  
  # Code generation
  build_runner: ^2.4.8
  
  # Additional dev tools
  dart_code_metrics: ^5.7.6

flutter:
  uses-material-design: true

  # Uncomment and configure assets when needed
  # assets:
  #   - assets/images/
  #   - assets/icons/

  # Uncomment and configure fonts when needed
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: assets/fonts/CustomFont-Regular.ttf
  #       - asset: assets/fonts/CustomFont-Bold.ttf
  #         weight: 700