// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiBVye_Jru8BLq96LeLhkNpbOhyHkLM6A',
    appId: '1:439220866294:web:8c0cbf6baab63890ccb0d7',
    messagingSenderId: '439220866294',
    projectId: 'finale-813d8',
    authDomain: 'finale-813d8.firebaseapp.com',
    storageBucket: 'finale-813d8.firebasestorage.app',
    measurementId: 'G-YH8GCME2J8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBHOMeChWTwEpN3v3Zzh5DmArsGtNtVzE',
    appId: '1:439220866294:android:7bc08aa97242f1f4ccb0d7',
    messagingSenderId: '439220866294',
    projectId: 'finale-813d8',
    storageBucket: 'finale-813d8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRIhVMst9IeroAPW_ae5pK3XTJjHoTBI8',
    appId: '1:439220866294:ios:c66d76f852b078faccb0d7',
    messagingSenderId: '439220866294',
    projectId: 'finale-813d8',
    storageBucket: 'finale-813d8.firebasestorage.app',
    iosBundleId: 'com.example.finale',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRIhVMst9IeroAPW_ae5pK3XTJjHoTBI8',
    appId: '1:439220866294:ios:c66d76f852b078faccb0d7',
    messagingSenderId: '439220866294',
    projectId: 'finale-813d8',
    storageBucket: 'finale-813d8.firebasestorage.app',
    iosBundleId: 'com.example.finale',
  );

}